//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUser()
        {
            this.UserHistory = new HashSet<UserHistory>();
            this.UserExercise = new HashSet<UserExercise>();
            this.UserFood = new HashSet<UserFood>();
        }
    
        public int UserID { get; set; }
        public string UName { get; set; }
        public Nullable<int> UWeight { get; set; }
        public Nullable<int> UHeight { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> UStatus { get; set; }
        public string Passwrd { get; set; }
        public string Username { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> ComsumedCalo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserHistory> UserHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserExercise> UserExercise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFood> UserFood { get; set; }
    }
}
