//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLMAEntities : DbContext
    {
        public QLMAEntities()
            : base("name=QLMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exercise> Exercise { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<FUser> FUser { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserExercise> UserExercise { get; set; }
        public virtual DbSet<UserFood> UserFood { get; set; }
        public virtual DbSet<UserHistory> UserHistory { get; set; }
    }
}
