//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExercise
    {
        public int UserID { get; set; }
        public int ExID { get; set; }
        public Nullable<int> Favourite { get; set; }
    
        public virtual Exercise Exercise { get; set; }
        public virtual FUser FUser { get; set; }
    }
}
